# File: ventaxia_ha/services.yaml

set_airflow_mode:
  name: Set Airflow Mode
  description: Set the airflow mode with a specific duration
  target:
    device:
      integration: ventaxia_iot
  fields:
    mode:
      name: Mode
      description: The airflow mode to set
      required: true
      selector:
        select:
          options:
            - label: "Reset/Cancel"
              value: "reset"
            - label: "Normal"
              value: "normal"  
            - label: "Boost"
              value: "boost"
            - label: "Purge"
              value: "purge"
    duration:
      name: Duration
      description: Duration in minutes (0 for reset only)
      required: true
      selector:
        select:
          options:
            - label: "0 minutes (reset only)"
              value: 0
            - label: "15 minutes"
              value: 15
            - label: "30 minutes" 
              value: 30
            - label: "45 minutes"
              value: 45
            - label: "60 minutes"
              value: 60