name: Test Suite

on:
  workflow_dispatch: # Only runs manually

env:
  DEFAULT_PYTHON: 3.11

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.2.2"
      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: "actions/setup-python@v5"
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install requirements
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install -r requirements_test.txt
      - name: Tests suite
        run: |
          pytest \
            --timeout=9 \
            --durations=10 \
            -n auto \
            -p no:sugar \
            tests
